// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function FibonacciEven(n) {
    let last = 2;
    let secondToLast = 1;
    let next = 3;
    let sum = 2;

    do {
        if(next % 2 == 0) {
            sum += next;
        }

        secondToLast = last;
        last = next;
        next = last + secondToLast;
    }
    while (next <= n )
        
    return sum;
}

console.log(FibonacciEven(4000000))